server:
  port: 8082
spring:
  application:
    name: spring-cloud-zookeeper
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active:
    - dev
---

spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true